// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzlnCLPGe409uSwO1HQJNqzu6TVUXwDhQ',
    appId: '1:935841880414:web:e21fcf2ce1c3e071d597cf',
    messagingSenderId: '935841880414',
    projectId: 'audiobook-9fd5e',
    authDomain: 'audiobook-9fd5e.firebaseapp.com',
    storageBucket: 'audiobook-9fd5e.appspot.com',
    measurementId: 'G-SCQGL33L96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZaxCrqwhaGFuz_9HDHeWf-TI5j-dNZKM',
    appId: '1:935841880414:android:aad0b0ecf071a934d597cf',
    messagingSenderId: '935841880414',
    projectId: 'audiobook-9fd5e',
    storageBucket: 'audiobook-9fd5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDedKpwEupsyF8odp92f-1hDIRAQaoqHuQ',
    appId: '1:935841880414:ios:3d39812d10ac8e27d597cf',
    messagingSenderId: '935841880414',
    projectId: 'audiobook-9fd5e',
    storageBucket: 'audiobook-9fd5e.appspot.com',
    iosBundleId: 'com.example.audioBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDedKpwEupsyF8odp92f-1hDIRAQaoqHuQ',
    appId: '1:935841880414:ios:3d39812d10ac8e27d597cf',
    messagingSenderId: '935841880414',
    projectId: 'audiobook-9fd5e',
    storageBucket: 'audiobook-9fd5e.appspot.com',
    iosBundleId: 'com.example.audioBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzlnCLPGe409uSwO1HQJNqzu6TVUXwDhQ',
    appId: '1:935841880414:web:4e42823c563a15d9d597cf',
    messagingSenderId: '935841880414',
    projectId: 'audiobook-9fd5e',
    authDomain: 'audiobook-9fd5e.firebaseapp.com',
    storageBucket: 'audiobook-9fd5e.appspot.com',
    measurementId: 'G-96P3NLDBC8',
  );
}
